# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/app_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        MainWindow.setMinimumSize(QtCore.QSize(400, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 3, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.update_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.update_label.setFont(font)
        self.update_label.setObjectName("update_label")
        self.verticalLayout_2.addWidget(self.update_label)
        self.process_frame = QtWidgets.QFrame(self.centralwidget)
        self.process_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.process_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.process_frame.setObjectName("process_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.process_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.process_label = QtWidgets.QLabel(self.process_frame)
        self.process_label.setObjectName("process_label")
        self.verticalLayout.addWidget(self.process_label)
        self.progressBar = QtWidgets.QProgressBar(self.process_frame)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_2.addWidget(self.process_frame)
        spacerItem1 = QtWidgets.QSpacerItem(20, 4, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.buttons_frame = QtWidgets.QFrame(self.centralwidget)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons_frame.setObjectName("buttons_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.buttons_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.open_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        self.open_pushButton.setEnabled(False)
        self.open_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.open_pushButton.setObjectName("open_pushButton")
        self.horizontalLayout.addWidget(self.open_pushButton)
        self.exit_pushButton = QtWidgets.QPushButton(self.buttons_frame)
        self.exit_pushButton.setEnabled(False)
        self.exit_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.exit_pushButton.setObjectName("exit_pushButton")
        self.horizontalLayout.addWidget(self.exit_pushButton)
        self.verticalLayout_2.addWidget(self.buttons_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.update_label.setText(_translate("MainWindow", "Обновление"))
        self.process_label.setText(_translate("MainWindow", "Процесс:"))
        self.open_pushButton.setText(_translate("MainWindow", "Открыть"))
        self.exit_pushButton.setText(_translate("MainWindow", "Выход"))
